/**
 * Targeted seed script for SmartClean project only.
 * Uses real Cloudinary URLs from prisma/smartclean-images.json
 * (generated by extract-smartclean-images.ts from the base64 images in smartclean.md).
 * Run with: npx tsx prisma/seed-smartclean.ts
 */
import { config } from "dotenv";
import { resolve } from "path";
import * as fs from "fs";

// Load .env.local (Next.js convention) so DATABASE_URL is available
config({ path: resolve(process.cwd(), ".env.local") });
config(); // fallback to .env

import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL!;
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Seeding SmartClean project with real screenshots...");

  // Load the image map produced by extract-smartclean-images.ts
  const imagesPath = resolve(process.cwd(), "prisma/smartclean-images.json");
  if (!fs.existsSync(imagesPath)) {
    throw new Error(
      "prisma/smartclean-images.json not found. Run extract-smartclean-images.ts first."
    );
  }
  const img: Record<string, string> = JSON.parse(
    fs.readFileSync(imagesPath, "utf8")
  );
  console.log(`  ✓ Loaded ${Object.keys(img).length} Cloudinary image URLs`);

  // ─────────────────────────────────────────────────────────────────────────
  // Image categorisation (based on smartclean.md document structure):
  //  image1–2   = Cover / logo
  //  image3–5   = Admin: login + dashboard
  //  image6–11  = Admin: KPI & Gains
  //  image12–13 = Admin: pricing settings
  //  image14–34 = Admin: user management
  //  image35–77 = Admin: requests & worksites
  //  image78–91 = Admin: time-clock management
  //  image92–98 = Admin: contracts
  //  image99–108 = Admin: schedule & reports
  //  image109–147 = Client portal
  //  image148–167 = Sector manager portal
  //  image168–190 = Agent mobile app
  // ─────────────────────────────────────────────────────────────────────────

  const posterImage = img["image3"] ?? null; // Admin dashboard as poster

  // Web app screenshots (admin + client + sector manager — landscape/tablet UI)
  const webAppImages: string[] = [
    img["image3"],
    img["image4"],
    img["image5"],
    img["image6"],
    img["image7"],
    img["image8"],
    img["image9"],
    img["image10"],
    img["image11"],
    img["image12"],
    img["image13"],
    img["image14"],
    img["image15"],
    img["image16"],
    img["image20"],
    img["image21"],
    img["image22"],
    img["image23"],
    img["image24"],
    img["image25"],
    img["image26"],
    img["image27"],
    img["image28"],
    img["image31"],
    img["image32"],
    img["image33"],
    img["image35"],
    img["image36"],
    img["image37"],
    img["image40"],
    img["image41"],
    img["image42"],
    img["image43"],
    img["image47"],
    img["image48"],
    img["image49"],
    img["image50"],
    img["image61"],
    img["image62"],
    img["image63"],
    img["image66"],
    img["image67"],
    img["image68"],
    img["image71"],
    img["image72"],
    img["image73"],
    img["image74"],
    img["image75"],
    img["image76"],
    img["image78"],
    img["image79"],
    img["image80"],
    img["image81"],
    img["image82"],
    img["image83"],
    img["image84"],
    img["image85"],
    img["image86"],
    img["image87"],
    img["image88"],
    img["image89"],
    img["image92"],
    img["image93"],
    img["image94"],
    img["image95"],
    img["image99"],
    img["image100"],
    img["image101"],
    img["image102"],
    img["image103"],
    img["image104"],
    img["image105"],
    img["image106"],
    img["image107"],
    img["image108"],
    img["image109"],
    img["image110"],
    img["image111"],
    img["image112"],
    img["image113"],
    img["image114"],
    img["image115"],
    img["image116"],
    img["image117"],
    img["image118"],
    img["image119"],
    img["image120"],
    img["image124"],
    img["image125"],
    img["image126"],
    img["image127"],
    img["image130"],
    img["image131"],
    img["image132"],
    img["image133"],
    img["image135"],
    img["image136"],
    img["image148"],
    img["image149"],
    img["image150"],
    img["image151"],
    img["image152"],
    img["image153"],
    img["image154"],
    img["image155"],
    img["image156"],
    img["image157"],
    img["image158"],
    img["image159"],
    img["image160"],
    img["image161"],
    img["image162"],
    img["image163"],
    img["image164"],
    img["image165"],
    img["image166"],
    img["image167"],
  ].filter(Boolean) as string[];

  // Mobile app screenshots (agent app — portrait UI)
  const mobileAppImages: string[] = [
    img["image168"],
    img["image169"],
    img["image170"],
    img["image171"],
    img["image172"],
    img["image173"],
    img["image174"],
    img["image175"],
    img["image176"],
    img["image177"],
    img["image178"],
    img["image179"],
    img["image180"],
    img["image181"],
    img["image182"],
    img["image183"],
    img["image184"],
    img["image185"],
    img["image186"],
    img["image187"],
    img["image188"],
    img["image189"],
    img["image190"],
  ].filter(Boolean) as string[];

  console.log(`  Web screenshots: ${webAppImages.length}`);
  console.log(`  Mobile screenshots: ${mobileAppImages.length}`);

  // ─────────────────────────────────────────────────────────────────────────
  // Upsert the SmartClean project
  // ─────────────────────────────────────────────────────────────────────────
  const smartcleanData = {
    titleEn: "SmartClean",
    titleFr: "SmartClean",
    subtitleEn:
      "Enterprise cleaning services management platform with multi-platform support",
    subtitleFr:
      "Plateforme de gestion de services de nettoyage d'entreprise avec support multi-plateforme",
    descriptionEn:
      "SmartClean is a comprehensive B2B cleaning services management platform developed for a France-based client. The system includes a web admin panel, mobile apps for Android/iOS (agents and sector managers), and a robust Django REST Framework backend. Key features include: GPS-based time clock with photo proof, recurring/one-time job scheduling, contract management, financial KPIs dashboard, FCM push notifications, and real-time alerts. Implemented full CI/CD pipeline with Docker Registry deploying to Azure, integrated Grafana & Prometheus for monitoring, and Sentry for error tracking. The platform manages cleaning agents, sector managers, clients, and administrators with role-based access control.",
    descriptionFr:
      "SmartClean est une plateforme complète de gestion de services de nettoyage B2B développée pour un client basé en France. Le système comprend un panneau d'administration web, des applications mobiles pour Android/iOS (agents et responsables de secteur), et un backend robuste Django REST Framework. Les fonctionnalités clés incluent : pointage GPS avec preuve photo, planification de tâches récurrentes/ponctuelles, gestion des contrats, tableau de bord KPIs financiers, notifications push FCM, et alertes en temps réel. Implémenté un pipeline CI/CD complet avec Docker Registry déployant sur Azure, intégré Grafana et Prometheus pour la surveillance, et Sentry pour le suivi des erreurs.",
    keyFeaturesEn: {
      "Multi-Platform":
        "Web admin panel + Android & iOS apps built with Flutter",
      "GPS Time Clock":
        "Agent check-in/check-out with GPS location and photo proof",
      "Smart Scheduling":
        "Recurring and one-time job scheduling with agent assignment and conflict detection",
      "Admin Dashboard":
        "Financial KPIs, contract management, global planning, and user administration",
      "CI/CD Pipeline": "Docker Registry → GitHub Actions → Azure deployment",
      Monitoring:
        "Grafana & Prometheus dashboards with real-time alerting + Sentry error tracking",
      Notifications:
        "Firebase Cloud Messaging (FCM) push notifications for agents",
      "Role-Based Access":
        "Admin, Sector Manager, Agent, and Client roles with fine-grained permissions",
    },
    keyFeaturesFr: {
      "Multi-Plateforme":
        "Panneau admin web + applications Android et iOS avec Flutter",
      "Pointage GPS":
        "Pointage des agents avec localisation GPS et preuve photo",
      "Planification Intelligente":
        "Tâches récurrentes et ponctuelles avec affectation des agents et détection des conflits",
      "Tableau de Bord Admin":
        "KPIs financiers, gestion des contrats, planning global et administration des utilisateurs",
      "Pipeline CI/CD": "Docker Registry → GitHub Actions → déploiement Azure",
      Surveillance:
        "Tableaux de bord Grafana & Prometheus avec alertes en temps réel + Sentry",
      Notifications:
        "Notifications push FCM (Firebase Cloud Messaging) pour les agents",
      "Contrôle d'Accès":
        "Rôles Admin, Responsable de Secteur, Agent et Client avec permissions granulaires",
    },
    dates: "Sep 2025 - Present",
    active: true,
    featured: true,
    order: 2,
    architectureDiagram: true,
    posterImage,
    mobileAppImages,
    webAppImages,
    technologies: [
      "Django REST Framework",
      "Flutter",
      "PostgreSQL",
      "Docker",
      "Azure",
      "Grafana",
      "Prometheus",
      "Sentry",
      "FCM",
      "Nginx Proxy Manager",
      "Adminer",
      "GitHub Actions",
    ],
  };

  const project = await prisma.project.upsert({
    where: { slug: "smartclean" },
    update: smartcleanData,
    create: {
      slug: "smartclean",
      ...smartcleanData,
    },
  });

  console.log(`\n✅ SmartClean project upserted (id: ${project.id})`);
  console.log(`   Poster: ${project.posterImage}`);
  console.log(`   Web images: ${project.webAppImages.length}`);
  console.log(`   Mobile images: ${project.mobileAppImages.length}`);
  console.log("\n🎉 SmartClean seed completed!");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding SmartClean:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
